### PR TITLE
wpforms pro support added

### PR DESCRIPTION
**Pull request by wiwi-websolutions**
Added WPForms Pro support.

### CODE REVIEW

**Comment by e271828-** [comment]
@wiwi-websolutions Thanks! Would you mind updating it to pass WPCS? (Click the Details for Travis CI to see errors)

**Comment by e271828-** [comment]
@wiwi-websolutions don't we want to swap the var names here (i.e. don't modify lite, since there are already users on it) and make pro the newly inserted one while leaving lite unchanged? Otherwise presumably it will mess up configurations for existing users.

**Comment by wiwi-websolutions** [comment]
You're right, my mistake! Let me fix that.

**Comment by e271828-** [comment]
> You're right, my mistake! Let me fix that.

Thanks, looks good! 

Do you mind doing a quick manual test just to ensure we aren't breaking the existing users: add released plugin, add wpf lite, enable + set keys, then update plugin to your branch and see if everything still works for wpf lite? 

Once you confirm that's working, will be ready for merge.

**Comment by wiwi-websolutions** [comment]
**WPForms Pro:** 
Been running my branch on a live site for about 2 days now, works like a charm 👍

**WPForms Lite:** 
Just tested my branch on a couple of sites that were already running the latest release, upgraded without any problems!

**Tested on:**
- WordPress 5.5.1
- WPForms Lite 1.6.2.3

**Comment by e271828-** [comment]
> **WPForms Pro:**
> Been running my branch on a live site for about 2 days now, works like a charm 👍
> 
> **WPForms Lite:**
> Just tested my branch on a couple of sites that were already running the latest release, upgraded without any problems!
> 
> **Tested on:**
> 
> * WordPress 5.5.1
> * WPForms Lite 1.6.2.3

Great!

**Pull request merged**
