### PR TITLE
Add ultimate member integration

### LINKED ISSUE #155: Ultimate Member
Compatibility with Ultimate Member.

I wanted to know if it was possible to add hcapcha in Ultimate Member in any way in order to verify people at login and registration.

### PR DESCRIPTION
**Pull request by TheZoker**
Adds [ultimate member](https://ultimatemember.com/) plugin support 

I also added a check, that verifies that the hcaptcha call was really made by wordpress native form. 
Since Ultimate Member uses wordpress hooks to verify login, this triggers the hcaptcha verification twice, leading to errors. After adding this check, everything works as expected. 

Closes #155

### CODE REVIEW

**Comment by TheZoker** [comment]
Thanks @kagg-design for the refactor! Should I look into the CI failure or do you want to work on that?

**Comment by kagg-design** [comment]
> Thanks @kagg-design for the refactor! Should I look into the CI failure or do you want to work on that? 

I see some other issues as well. So, I will proceed with this PR further and merge it.

**Comment by kagg-design** [comment]
Many thanks, @TheZoker, for providing the initial solution. I have fixed minor issues and covered them with tests.

Now your code is merged into the v1.17.0 branch and will be released soon.

**Comment by TheZoker** [comment]
Thank you very much! Looking forward to the update!

**Pull request closed without merging**
