### PR TITLE
Fix call verify CAPTCHA twice

### PR DESCRIPTION
**Pull request by thinhbuzz**
- use common functions for both default and wc lost password page
- change `allow_password_reset` filter to `lostpassword_post` action because `allow_password_reset` will be call twice in `WC_Shortcode_My_Account > retrieve_password

TODO:
- [x] Double-check another form
- [x] Move the logic request to hcaptcha server into the common file
- [x] Implement language file

### CODE REVIEW

**Comment by e271828-** [comment]
@thinhbuzz thanks, looks like a good start! Just tag me when ready for review.

**Comment by thinhbuzz** [comment]
@e271828- pls help me verify this PR. I have tested with default and WC forms, other forms I haven't. But in other forms, I only move out verify logic.

**Comment by e271828-** [comment]
@thinhbuzz can you run through the other form plugins quickly? Once you've tested them at least one time, then it's probably time for other people to do so :)

**Comment by thinhbuzz** [comment]
I have checked almost every plugin except:
- Jetpack: because I don't have a real domain for setup this plugin
- WPForo: because of the load form via Ajax, the current code will never work. I think it is out of scope by PR

**Comment by e271828-** [comment]
> I have checked almost every plugin except:
> 
> * Jetpack: because I don't have a real domain for setup this plugin
> * WPForo: because of the load form via Ajax, the current code will never work. I think it is out of scope by PR

Thanks, appreciate it. Will run through everything and land shortly.

**Pull request merged**
